package lesson_1

const val TOTAL_TIME_SPENT_IN_SPACE_IN_SECONDS: Int = 6480
const val SECONDS_IN_MINUTE_AND_MINUTES_IN_HOUR: Int = 60


fun main() {
    val seconds: Int = TOTAL_TIME_SPENT_IN_SPACE_IN_SECONDS % SECONDS_IN_MINUTE_AND_MINUTES_IN_HOUR
    val minutes: Int =
        TOTAL_TIME_SPENT_IN_SPACE_IN_SECONDS / SECONDS_IN_MINUTE_AND_MINUTES_IN_HOUR % SECONDS_IN_MINUTE_AND_MINUTES_IN_HOUR
    val hours: Int =
        TOTAL_TIME_SPENT_IN_SPACE_IN_SECONDS / SECONDS_IN_MINUTE_AND_MINUTES_IN_HOUR / SECONDS_IN_MINUTE_AND_MINUTES_IN_HOUR

    println("%02d:%02d:%02d".format(hours, minutes, seconds))
}